package rs.pupin.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import rs.pupin.model.Polygon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POLYGON".
*/
public class PolygonDao extends AbstractDao<Polygon, Long> {

    public static final String TABLENAME = "POLYGON";

    /**
     * Properties of entity Polygon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Lat = new Property(1, Double.class, "lat", false, "LAT");
        public final static Property Longit = new Property(2, Double.class, "longit", false, "LONGIT");
        public final static Property Markers = new Property(3, String.class, "markers", false, "MARKERS");
        public final static Property Map_layer_id = new Property(4, Long.class, "map_layer_id", false, "MAP_LAYER_ID");
    };

    private DaoSession daoSession;


    public PolygonDao(DaoConfig config) {
        super(config);
    }
    
    public PolygonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POLYGON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LAT\" REAL," + // 1: lat
                "\"LONGIT\" REAL," + // 2: longit
                "\"MARKERS\" TEXT," + // 3: markers
                "\"MAP_LAYER_ID\" INTEGER);"); // 4: map_layer_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POLYGON\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Polygon entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(2, lat);
        }
 
        Double longit = entity.getLongit();
        if (longit != null) {
            stmt.bindDouble(3, longit);
        }
 
        String markers = entity.getMarkers();
        if (markers != null) {
            stmt.bindString(4, markers);
        }
 
        Long map_layer_id = entity.getMap_layer_id();
        if (map_layer_id != null) {
            stmt.bindLong(5, map_layer_id);
        }
    }

    @Override
    protected void attachEntity(Polygon entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Polygon readEntity(Cursor cursor, int offset) {
        Polygon entity = new Polygon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // lat
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // longit
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // markers
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // map_layer_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Polygon entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLat(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setLongit(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setMarkers(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMap_layer_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Polygon entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Polygon entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLayerDao().getAllColumns());
            builder.append(" FROM POLYGON T");
            builder.append(" LEFT JOIN LAYER T0 ON T.\"MAP_LAYER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Polygon loadCurrentDeep(Cursor cursor, boolean lock) {
        Polygon entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Layer layer = loadCurrentOther(daoSession.getLayerDao(), cursor, offset);
        entity.setLayer(layer);

        return entity;    
    }

    public Polygon loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Polygon> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Polygon> list = new ArrayList<Polygon>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Polygon> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Polygon> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
